
package unwrapped;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IpAddressSearchWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IpAddressSearchWebServiceSoap {


    /**
     * <br /><h3>ͨ������IP��ַ��ѯ���ҡ����С������ߵ���Ϣ��û��ע�����ҵ�Ϊ�й�</h3><p>���������IP��ַ���Զ��滻 " ��" Ϊ "."�����������ݣ� һ��һά�ַ�������String(1)��String(0) = IP��ַ��String(1) = ��ѯ�������ʾ��Ϣ</p><br />
     * 
     * @param parameters
     * @return
     *     returns ipC.GetCountryCityByIpResponse
     */
    @WebMethod(action = "http://WebXml.com.cn/getCountryCityByIp")
    @WebResult(name = "getCountryCityByIpResponse", targetNamespace = "http://WebXml.com.cn/", partName = "parameters")
    public GetCountryCityByIpResponse getCountryCityByIp(
            @WebParam(name = "getCountryCityByIp", targetNamespace = "http://WebXml.com.cn/", partName = "parameters")
                    GetCountryCityByIp parameters);

    /**
     * <br /><h3>�������IP��ַ�͵�ַ��Ϣ</h3><p>����������ޣ��������ݣ� һ��һά�ַ�������String(1)��String(0) = IP��ַ��String(1) = ��ַ��Ϣ</p><br />
     * 
     * @param parameters
     * @return
     *     returns ipC.GetGeoIPContextResponse
     */
    @WebMethod(action = "http://WebXml.com.cn/getGeoIPContext")
    @WebResult(name = "getGeoIPContextResponse", targetNamespace = "http://WebXml.com.cn/", partName = "parameters")
    public GetGeoIPContextResponse getGeoIPContext(
            @WebParam(name = "getGeoIPContext", targetNamespace = "http://WebXml.com.cn/", partName = "parameters")
                    GetGeoIPContext parameters);

    /**
     * <br /><h3>��ñ�IP��ַ���� WEB ��������ݿ�汾����ʱ��</h3><p>����������ޣ�������� String</p><br />
     * 
     * @param parameters
     * @return
     *     returns ipC.GetVersionTimeResponse
     */
    @WebMethod(action = "http://WebXml.com.cn/getVersionTime")
    @WebResult(name = "getVersionTimeResponse", targetNamespace = "http://WebXml.com.cn/", partName = "parameters")
    public GetVersionTimeResponse getVersionTime(
            @WebParam(name = "getVersionTime", targetNamespace = "http://WebXml.com.cn/", partName = "parameters")
                    GetVersionTime parameters);

}
